---

sudo: required

language: bash

services:
  - docker

before_install:
  # clean install latest (tmp for docker 1.10.x)
  - sudo apt-get -y purge docker-engine
  - sudo apt-get update
  - sudo apt-get -y install curl docker-engine

install:
  - docker build -t fcrepo/release release/
  - docker run --name fcrepo-release -d -p 8080:8080 fcrepo/release

before_script:
  - sleep 30

script:
  - docker ps | grep fcrepo-release
  - curl http://localhost:8080/fcrepo/rest

