---
sudo: required

language: bash

services:
  - docker

install:
  - docker build -t fcrepo:latest build/
  - docker run --name fcrepo -d -p 8080:8080 fcrepo:latest

before_script:
  - sleep 30

script:
  - docker ps | grep fcrepo
  - curl http://localhost:8080/fcrepo/rest
